version: "3.7"

services:
  backend:
    build: ./backend
    ports:
      - 8085:8085
    environment:
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USERNAME: postgres
    networks:
      - local
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - local
  
  frontend:
    build: ./frontend
    ports:
      - 8081:80
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  postgres:
    driver: local
